/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.conn;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import controller.ReservaDao;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import model.Reserva;

/**
 *
 * @author joelmir
 */
public class PrimeiraTela_Reserva extends javax.swing.JFrame {
    ReservaDao Rdao = new ReservaDao() {};
    
    int Buscar_M = 0;
    int Buscar_C = -1;
    /**
     * Creates new form Principal
     */
    public PrimeiraTela_Reserva() {
        
        
        initComponents();  
        setExtendedState(MAXIMIZED_BOTH);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_periodo_ = new javax.swing.ButtonGroup();
        jPanel_principal_ = new javax.swing.JPanel();
        jdp_principal = new javax.swing.JDesktopPane();
        jButton_ConfirmarReserva_ = new javax.swing.JButton();
        jButton_Sair_ = new javax.swing.JButton();
        jLabel_TITULO = new javax.swing.JLabel();
        jLabel_dataReserva = new javax.swing.JLabel();
        jTextField_data = new javax.swing.JTextField();
        jLabel_QtdPessoas_ = new javax.swing.JLabel();
        jTextField_QtdPessoas = new javax.swing.JTextField();
        jButton_BuscarMesa_ = new javax.swing.JButton();
        jButton_BuscarCliente_ = new javax.swing.JButton();
        jButton_Limpar_ = new javax.swing.JButton();
        jLabel_periodo_ = new javax.swing.JLabel();
        jRadioButton_CafedaManha = new javax.swing.JRadioButton();
        jRadioButton_Almoco = new javax.swing.JRadioButton();
        jRadioButton_Noite = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_CadastroFuncionario_ = new javax.swing.JMenu();
        jMenu_CadastroCliente_ = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas Joelmir");
        setResizable(false);

        javax.swing.GroupLayout jPanel_principal_Layout = new javax.swing.GroupLayout(jPanel_principal_);
        jPanel_principal_.setLayout(jPanel_principal_Layout);
        jPanel_principal_Layout.setHorizontalGroup(
            jPanel_principal_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1336, Short.MAX_VALUE)
        );
        jPanel_principal_Layout.setVerticalGroup(
            jPanel_principal_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jdp_principal.setBackground(java.awt.SystemColor.activeCaption);
        jdp_principal.setForeground(new java.awt.Color(51, 51, 51));
        jdp_principal.setName(""); // NOI18N

        jButton_ConfirmarReserva_.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton_ConfirmarReserva_.setText("Confirmar Reserva");
        jButton_ConfirmarReserva_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConfirmarReserva_ActionPerformed(evt);
            }
        });

        jButton_Sair_.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jButton_Sair_.setText("Sair");
        jButton_Sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sair_ActionPerformed(evt);
            }
        });

        jLabel_TITULO.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel_TITULO.setText("CADASTRO RESERVAS:");

        jLabel_dataReserva.setText("Data Reserva:");

        jLabel_QtdPessoas_.setText("Quantidade pessoas");

        jButton_BuscarMesa_.setText("Selecione Mesa");
        jButton_BuscarMesa_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarMesa_ActionPerformed(evt);
            }
        });

        jButton_BuscarCliente_.setText("Cliente");
        jButton_BuscarCliente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarCliente_ActionPerformed(evt);
            }
        });

        jButton_Limpar_.setText("Limpar");
        jButton_Limpar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Limpar_ActionPerformed(evt);
            }
        });

        jLabel_periodo_.setText("Escollha:");

        buttonGroup_periodo_.add(jRadioButton_CafedaManha);
        jRadioButton_CafedaManha.setText("Café da Manhã");

        buttonGroup_periodo_.add(jRadioButton_Almoco);
        jRadioButton_Almoco.setText("Almoço");

        buttonGroup_periodo_.add(jRadioButton_Noite);
        jRadioButton_Noite.setText("Noite");

        jdp_principal.setLayer(jButton_ConfirmarReserva_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_Sair_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_TITULO, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_dataReserva, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_data, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_QtdPessoas_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jTextField_QtdPessoas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_BuscarMesa_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_BuscarCliente_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_Limpar_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jLabel_periodo_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jRadioButton_CafedaManha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jRadioButton_Almoco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jRadioButton_Noite, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdp_principalLayout = new javax.swing.GroupLayout(jdp_principal);
        jdp_principal.setLayout(jdp_principalLayout);
        jdp_principalLayout.setHorizontalGroup(
            jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp_principalLayout.createSequentialGroup()
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(502, 502, 502)
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_BuscarMesa_, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jdp_principalLayout.createSequentialGroup()
                                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdp_principalLayout.createSequentialGroup()
                                        .addComponent(jLabel_QtdPessoas_)
                                        .addGap(27, 27, 27))
                                    .addGroup(jdp_principalLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_periodo_)
                                            .addComponent(jLabel_dataReserva))
                                        .addGap(68, 68, 68)))
                                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_data, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_QtdPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton_Noite)
                                    .addComponent(jRadioButton_Almoco)
                                    .addComponent(jRadioButton_CafedaManha)))
                            .addGroup(jdp_principalLayout.createSequentialGroup()
                                .addComponent(jButton_BuscarCliente_, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))))
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(534, 534, 534)
                        .addComponent(jButton_ConfirmarReserva_, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jdp_principalLayout.createSequentialGroup()
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(566, 566, 566)
                        .addComponent(jLabel_TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(577, 577, 577)
                        .addComponent(jButton_Limpar_, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(602, 602, 602)
                        .addComponent(jButton_Sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdp_principalLayout.setVerticalGroup(
            jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp_principalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel_TITULO)
                .addGap(31, 31, 31)
                .addComponent(jButton_BuscarMesa_, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_data, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_dataReserva))
                .addGap(23, 23, 23)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_CafedaManha)
                    .addComponent(jLabel_periodo_))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_Almoco)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_Noite)
                .addGap(32, 32, 32)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_QtdPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_QtdPessoas_))
                .addGap(38, 38, 38)
                .addComponent(jButton_BuscarCliente_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton_ConfirmarReserva_, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Limpar_)
                .addGap(18, 18, 18)
                .addComponent(jButton_Sair_)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jMenu_CadastroFuncionario_.setText("Funcionario");
        jMenu_CadastroFuncionario_.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jMenu_CadastroFuncionario_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu_CadastroFuncionario_MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu_CadastroFuncionario_);

        jMenu_CadastroCliente_.setText("Cadastro Cliente");
        jMenu_CadastroCliente_.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jMenu_CadastroCliente_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu_CadastroCliente_MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu_CadastroCliente_);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_principal_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jdp_principal)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdp_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_principal_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ConfirmarReserva_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConfirmarReserva_ActionPerformed
     
        this.CadastroReserva();
        
    }//GEN-LAST:event_jButton_ConfirmarReserva_ActionPerformed

    private void jButton_Sair_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sair_ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_Sair_ActionPerformed

    private void jButton_BuscarMesa_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarMesa_ActionPerformed
        
        int mesa = Integer.parseInt(JOptionPane.showInputDialog("Informe Numero da Mesa entre 1 - 5"));
         
        if(mesa > 0 && mesa < 6){
            Buscar_M = mesa;
            JOptionPane.showMessageDialog(null, "Mesa Confirmado" );
        }else{
            JOptionPane.showMessageDialog(null, "Escolha Mesa entre 1 a 5" );
        }
    }//GEN-LAST:event_jButton_BuscarMesa_ActionPerformed

    private void jMenu_CadastroFuncionario_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_CadastroFuncionario_MousePressed
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundaTela_LoginFuncionario().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_jMenu_CadastroFuncionario_MousePressed

    private void jMenu_CadastroCliente_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_CadastroCliente_MousePressed
        
        ClienteV v = new ClienteV();
        jdp_principal.add(v);
        v.setVisible(true);
        
    }//GEN-LAST:event_jMenu_CadastroCliente_MousePressed

    private void jButton_Limpar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Limpar_ActionPerformed
        limpar();
    }//GEN-LAST:event_jButton_Limpar_ActionPerformed

    private void jButton_BuscarCliente_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarCliente_ActionPerformed
        
        String CPF = JOptionPane.showInputDialog("Informe o CPF");
        String sql2 = "SELECT idcliente FROM Cliente WHERE cpf = ?";
        
        try {
            PreparedStatement ps = conn.getConexao().prepareStatement(sql2);
            ps.setString(1, CPF);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                Buscar_C = rs.getInt("idcliente");
                //JOptionPane.showMessageDialog(null, "ID  " +Buscar_IdV);
                JOptionPane.showMessageDialog(null, "Cliente Confirmado!" );
            }else{
                JOptionPane.showMessageDialog(null, "Cliente nao Cadastrado!" );
            }
            
            ps.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na inserção: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton_BuscarCliente_ActionPerformed

    public void limpar(){
        
         jTextField_data.setText("");
         jTextField_QtdPessoas.setText("");
       
     }
     
    public void CadastroReserva(){
        
        Reserva r = new Reserva();
              
        // Para verificar qual opção foi selecionada buttonGroup:
        String periodoSelecionado = "";
        for (Enumeration<AbstractButton> buttons = buttonGroup_periodo_.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                periodoSelecionado = button.getText();
                break;
            }
        }
        
         String sqlV = "SELECT mesa,datareserva,periodo FROM Reservas WHERE mesa=? AND datareserva=? AND periodo=?";        
        try {
            PreparedStatement ps = conn.getConexao().prepareStatement(sqlV);
            ps.setInt(1, Buscar_M);
            ps.setString(2, jTextField_data.getText());
            ps.setString(3, periodoSelecionado);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()){
                
             JOptionPane.showMessageDialog(null, "Mesa Indisponivel!" ); 
             
            }else{
                
                r.setMesa(Buscar_M);
                r.setDatareserva(jTextField_data.getText());
                r.setPeriodo(periodoSelecionado);
                r.setQtdpessoas(Integer.parseInt(jTextField_QtdPessoas.getText().toString()));
                r.setCliente(Buscar_C);
                
                limpar();
                
            }
            
           
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"ERRO SQL:\n"+e);
        }
        
        Rdao.inserir(r);
    }
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeiraTela_Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeiraTela_Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeiraTela_Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeiraTela_Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimeiraTela_Reserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_periodo_;
    private javax.swing.JButton jButton_BuscarCliente_;
    private javax.swing.JButton jButton_BuscarMesa_;
    private javax.swing.JButton jButton_ConfirmarReserva_;
    private javax.swing.JButton jButton_Limpar_;
    private javax.swing.JButton jButton_Sair_;
    private javax.swing.JLabel jLabel_QtdPessoas_;
    private javax.swing.JLabel jLabel_TITULO;
    private javax.swing.JLabel jLabel_dataReserva;
    private javax.swing.JLabel jLabel_periodo_;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_CadastroCliente_;
    private javax.swing.JMenu jMenu_CadastroFuncionario_;
    private javax.swing.JPanel jPanel_principal_;
    private javax.swing.JRadioButton jRadioButton_Almoco;
    private javax.swing.JRadioButton jRadioButton_CafedaManha;
    private javax.swing.JRadioButton jRadioButton_Noite;
    private javax.swing.JTextField jTextField_QtdPessoas;
    private javax.swing.JTextField jTextField_data;
    private javax.swing.JDesktopPane jdp_principal;
    // End of variables declaration//GEN-END:variables
}
