/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import controller.conn;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import view.ConsultarCliente;

/**
 *
 * @author joelmir
 */
public class TerceiraTela_Consultas extends javax.swing.JFrame {
  
    /**
     * Creates new form Principal
     */
    public TerceiraTela_Consultas() {
        initComponents(); 
        //Comando para abrir janela em tela cheia
        //setExtendedState(MAXIMIZED_BOTH);
        //setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_principal_ = new javax.swing.JPanel();
        jdp_principal = new javax.swing.JDesktopPane();
        jButton_fechar_ = new javax.swing.JButton();
        jButton_Reservas_ = new javax.swing.JButton();
        jButton_Cliente_ = new javax.swing.JButton();
        jButton_Mesas_ = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1_Funcionario = new javax.swing.JMenu();
        jMenuItem_CadatroFuncionario_ = new javax.swing.JMenuItem();
        jMenuItem_ConsultarFuncionario_ = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas Joelmir");

        javax.swing.GroupLayout jPanel_principal_Layout = new javax.swing.GroupLayout(jPanel_principal_);
        jPanel_principal_.setLayout(jPanel_principal_Layout);
        jPanel_principal_Layout.setHorizontalGroup(
            jPanel_principal_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1384, Short.MAX_VALUE)
        );
        jPanel_principal_Layout.setVerticalGroup(
            jPanel_principal_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jdp_principal.setBackground(java.awt.SystemColor.activeCaption);
        jdp_principal.setForeground(new java.awt.Color(51, 51, 51));
        jdp_principal.setName(""); // NOI18N

        jButton_fechar_.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jButton_fechar_.setText("Fechar");
        jButton_fechar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fechar_ActionPerformed(evt);
            }
        });

        jButton_Reservas_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 24)); // NOI18N
        jButton_Reservas_.setText("Consultar Reservas");
        jButton_Reservas_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Reservas_ActionPerformed(evt);
            }
        });

        jButton_Cliente_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 24)); // NOI18N
        jButton_Cliente_.setText("Consultar Cliente");
        jButton_Cliente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cliente_ActionPerformed(evt);
            }
        });

        jButton_Mesas_.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jButton_Mesas_.setText("Consulltar Mesa");
        jButton_Mesas_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Mesas_ActionPerformed(evt);
            }
        });

        jdp_principal.setLayer(jButton_fechar_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_Reservas_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_Cliente_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_Mesas_, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdp_principalLayout = new javax.swing.GroupLayout(jdp_principal);
        jdp_principal.setLayout(jdp_principalLayout);
        jdp_principalLayout.setHorizontalGroup(
            jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp_principalLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jButton_Reservas_, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Cliente_, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdp_principalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Mesas_, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton_fechar_, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(533, 533, 533))
        );
        jdp_principalLayout.setVerticalGroup(
            jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp_principalLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cliente_, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Reservas_, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(jButton_Mesas_, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(jButton_fechar_, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );

        jMenu1_Funcionario.setText("Funcionario");
        jMenu1_Funcionario.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N

        jMenuItem_CadatroFuncionario_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        jMenuItem_CadatroFuncionario_.setText("Cadastro Funcionario");
        jMenuItem_CadatroFuncionario_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CadatroFuncionario_ActionPerformed(evt);
            }
        });
        jMenu1_Funcionario.add(jMenuItem_CadatroFuncionario_);

        jMenuItem_ConsultarFuncionario_.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        jMenuItem_ConsultarFuncionario_.setText("Consultar Funcionario");
        jMenuItem_ConsultarFuncionario_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultarFuncionario_ActionPerformed(evt);
            }
        });
        jMenu1_Funcionario.add(jMenuItem_ConsultarFuncionario_);

        jMenuBar2.add(jMenu1_Funcionario);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_principal_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdp_principal))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdp_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_principal_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_fechar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fechar_ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_fechar_ActionPerformed

    private void jButton_Reservas_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Reservas_ActionPerformed
        
        ConsultarReserva cr = new ConsultarReserva();
        jdp_principal.add(cr);
        cr.setVisible(true);
                
    }//GEN-LAST:event_jButton_Reservas_ActionPerformed

    private void jButton_Cliente_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cliente_ActionPerformed
        
        ConsultarCliente c = new ConsultarCliente();
        jdp_principal.add(c);;
        c.setVisible(true);
        
    }//GEN-LAST:event_jButton_Cliente_ActionPerformed

    private void jMenuItem_CadatroFuncionario_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CadatroFuncionario_ActionPerformed
        
        CadastroFuncionarioLogin cf = new CadastroFuncionarioLogin();
        jdp_principal.add(cf);
        cf.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_CadatroFuncionario_ActionPerformed

    private void jMenuItem_ConsultarFuncionario_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarFuncionario_ActionPerformed
        
        ConsultarFuncionario cf = new ConsultarFuncionario();
        jdp_principal.add(cf);
        cf.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem_ConsultarFuncionario_ActionPerformed

    private void jButton_Mesas_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Mesas_ActionPerformed
        String sqlcpfM = "SELECT * FROM Reservas WHERE mesa = ?";
        this.BuscarTab(sqlcpfM);
        
    }//GEN-LAST:event_jButton_Mesas_ActionPerformed

    public void BuscarTab(String sql){
            //DefaultTableModel ModeloTab = new DefaultTableModel();
            DefaultTableModel ModeloTab = new DefaultTableModel();
        
           // Conectar ao banco de dados e obter dados da tabela
            String SQL = JOptionPane.showInputDialog("Digite Numero Mesa:");
            try {
                //JOptionPane.showMessageDialog(null,sql);
                PreparedStatement ps = conn.getConexao().prepareStatement(sql);
                ps.setString(1, SQL);
                ResultSet rs = ps.executeQuery();
                // Obter informações sobre as colunas
                ResultSetMetaData metaData = rs.getMetaData();
                int colCount = metaData.getColumnCount();
                // Adicionar colunas ao modelo
                for (int i = 1; i <= colCount; i++) {
                     ModeloTab.addColumn(metaData.getColumnName(i));
                }
                // Adicionar linhas ao modelo com dados do banco de dados
                while (rs.next()) {
                    Object[] rowData = new Object[colCount];
                    for (int i = 1; i <= colCount; i++) {
                        rowData[i - 1] = rs.getObject(i);
                    }
                    ModeloTab.addRow(rowData);
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Mesa nao Cadastrada!" );
                //dispose();
            }
            
            JTable tabela = new JTable(ModeloTab);
        
            JFrame frame = new JFrame("Consultar");
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.getContentPane().add(new JScrollPane(tabela));
            frame.pack();

            frame.setSize(1000, 600);

            //Comando para centralizar o frame
            frame.setLocationRelativeTo(null);

            frame.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TerceiraTela_Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TerceiraTela_Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TerceiraTela_Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TerceiraTela_Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TerceiraTela_Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cliente_;
    private javax.swing.JButton jButton_Mesas_;
    private javax.swing.JButton jButton_Reservas_;
    private javax.swing.JButton jButton_fechar_;
    private javax.swing.JMenu jMenu1_Funcionario;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem_CadatroFuncionario_;
    private javax.swing.JMenuItem jMenuItem_ConsultarFuncionario_;
    private javax.swing.JPanel jPanel_principal_;
    private javax.swing.JDesktopPane jdp_principal;
    // End of variables declaration//GEN-END:variables
}
